// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AuthResponse = {
    accessToken: string;
    accessTokenExpiresAt: string;
    user: UserInfo;
};

export type BackupInfo = {
    name: string;
    kind: BackupKind;
    createdAt: string;
    size: number;
    cmsVersion?: string | null;
    mediaCount?: number | null;
    error?: string | null;
};

export type BackupInterval = 'off' | 'daily' | 'weekly';

export type BackupKind = 'auto' | 'manual' | 'pre-restore' | 'upload';

export type BackupSettingsResponse = {
    interval: BackupInterval;
    timeOfDay: string;
    weekday: number;
    retention: number;
    lastRunAt?: string | null;
    lastError?: string | null;
    nextRunAt?: string | null;
    directory: string;
    hostPath?: string | null;
    freeBytes?: number | null;
    maxUploadBytes: number;
};

export type Block = {
    id: string;
    name: string;
    attributes: {
        [key: string]: unknown;
    };
    innerBlocks: Array<Block>;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type ConfigAddress = {
    street: string;
    postalCode: string;
    city: string;
    country: string;
};

export type ConfigEntry = {
    id: string;
    key: string;
    label: string;
    type: ConfigFieldType;
    value: string;
    address?: ConfigAddress | null;
};

export type ConfigEntryValue = {
    id: string;
    key: string;
    type: ConfigFieldType;
    value: string;
    address?: ConfigAddress | null;
};

export type ConfigFieldDef = {
    key: string;
    label: string;
    type: ConfigFieldType;
    required: boolean;
};

export type ConfigFieldType = 'text' | 'email' | 'phone' | 'link' | 'address';

export type ConfigGroupDef = {
    key: string;
    label: string;
    presets: Array<ConfigPresetDef>;
    defaults: Array<string>;
    required: Array<string>;
    allowCustom: boolean;
};

export type ConfigPresetDef = {
    key: string;
    label: string;
    type: ConfigFieldType;
};

export type ConfirmEmailRequest = {
    token: string;
};

export type CreateMenuRequest = {
    handle: string;
};

export type CreatePageRequest = {
    title: string;
    slug?: string | null;
    blocks?: Array<Block> | null;
};

export type FooterLink = {
    title: string;
    slug: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ImportPageRequest = {
    title: string;
    slug?: string | null;
    blocks: Array<Block>;
    metaTitle?: string | null;
    metaDescription?: string | null;
    tags?: Array<string> | null;
};

export type ImportPageResult = {
    page: PageDetail;
    missingMediaIds: Array<string>;
};

export type InstanceConfig = {
    publicAuth: boolean;
    excludedBlocks: Array<string>;
    siteConfig: SiteConfigSchema;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type MediaItem = {
    id: string;
    url: string;
    fileName: string;
    contentType: string;
    size: number;
    alt: string;
    createdAt: string;
};

export type MediaRef = {
    id: string;
    url: string;
    alt: string;
};

export type MenuDetail = {
    id: string;
    handle: string;
    items: Array<MenuItem>;
    createdAt: string;
    updatedAt: string;
};

export type MenuItem = {
    id: string;
    label: string;
    pageId?: string | null;
    url?: string | null;
    children: Array<MenuItem>;
};

export type MenuSummary = {
    id: string;
    handle: string;
    itemCount: number;
    updatedAt: string;
};

export type PageDetail = {
    id: string;
    title: string;
    slug: string;
    status: PageStatus;
    tags: Array<string>;
    blocks: Array<Block>;
    media: Array<MediaRef>;
    createdAt: string;
    updatedAt: string;
    publishedAt?: string | null;
    template?: string | null;
    locked: boolean;
    editable: boolean;
    metaTitle: string;
    metaDescription: string;
};

export type PageStatus = 'draft' | 'published';

export type PageSummary = {
    id: string;
    title: string;
    slug: string;
    status: PageStatus;
    tags: Array<string>;
    blockCount: number;
    createdAt: string;
    updatedAt: string;
    publishedAt?: string | null;
    locked: boolean;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type PublicMenu = {
    handle: string;
    items: Array<PublicMenuItem>;
};

export type PublicMenuItem = {
    label: string;
    slug?: string | null;
    url?: string | null;
    children: Array<PublicMenuItem>;
};

export type PublicPage = {
    title: string;
    slug: string;
    blocks: Array<Block>;
    media: Array<MediaRef>;
    publishedAt?: string | null;
    template?: string | null;
    metaTitle: string;
    metaDescription: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
    displayName?: string | null;
};

export type RequestVerificationRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    token: string;
    newPassword: string;
};

export type RestoreResult = {
    preRestoreBackup: string;
};

export type SiteConfigResponse = {
    fields: {
        [key: string]: string;
    };
    groups: {
        [key: string]: Array<ConfigEntry>;
    };
    logo?: MediaRef | null;
    icon?: MediaRef | null;
    shareImage?: MediaRef | null;
    updatedAt?: string | null;
    footerLinks: Array<FooterLink>;
};

export type SiteConfigSchema = {
    fields: Array<ConfigFieldDef>;
    groups: Array<ConfigGroupDef>;
};

export type StaffRegisterRequest = {
    email: string;
    password: string;
    displayName?: string | null;
    organizationId?: string | null;
    roles?: Array<string> | null;
};

export type TagUsage = {
    name: string;
    pageCount: number;
};

export type UpdateBackupSettingsRequest = {
    interval: BackupInterval;
    timeOfDay: string;
    weekday: number;
    retention: number;
};

export type UpdateMediaRequest = {
    alt?: string | null;
    fileName?: string | null;
};

export type UpdateMenuRequest = {
    items: Array<MenuItem>;
};

export type UpdatePageRequest = {
    title?: string | null;
    slug?: string | null;
    blocks?: Array<Block> | null;
    metaTitle?: string | null;
    metaDescription?: string | null;
};

export type UpdatePageTagsRequest = {
    tags: Array<string>;
};

export type UpdateProfileRequest = {
    displayName?: string | null;
};

export type UpdateSiteConfigRequest = {
    fields?: {
        [key: string]: string;
    } | null;
    groups?: {
        [key: string]: Array<ConfigEntryValue>;
    } | null;
    logoMediaId?: string | null;
    iconMediaId?: string | null;
    shareImageMediaId?: string | null;
};

export type UserInfo = {
    id: string;
    email: string;
    displayName?: string | null;
    userType: string;
    roles: Array<string>;
    organizationId?: string | null;
};

export type GetApiBackupsSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/backups/settings';
};

export type GetApiBackupsSettingsResponses = {
    /**
     * OK
     */
    200: BackupSettingsResponse;
};

export type GetApiBackupsSettingsResponse = GetApiBackupsSettingsResponses[keyof GetApiBackupsSettingsResponses];

export type PutApiBackupsSettingsData = {
    body?: UpdateBackupSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/backups/settings';
};

export type PutApiBackupsSettingsResponses = {
    /**
     * OK
     */
    200: BackupSettingsResponse;
};

export type PutApiBackupsSettingsResponse = PutApiBackupsSettingsResponses[keyof PutApiBackupsSettingsResponses];

export type GetApiBackupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/backups';
};

export type GetApiBackupsResponses = {
    /**
     * OK
     */
    200: Array<BackupInfo>;
};

export type GetApiBackupsResponse = GetApiBackupsResponses[keyof GetApiBackupsResponses];

export type PostApiBackupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/backups';
};

export type PostApiBackupsResponses = {
    /**
     * OK
     */
    200: BackupInfo;
};

export type PostApiBackupsResponse = PostApiBackupsResponses[keyof PostApiBackupsResponses];

export type DeleteApiBackupsByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/backups/{name}';
};

export type DeleteApiBackupsByNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBackupsByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/backups/{name}';
};

export type GetApiBackupsByNameResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetApiBackupsByNameResponse = GetApiBackupsByNameResponses[keyof GetApiBackupsByNameResponses];

export type PostApiBackupsUploadData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/backups/upload';
};

export type PostApiBackupsUploadResponses = {
    /**
     * OK
     */
    200: BackupInfo;
};

export type PostApiBackupsUploadResponse = PostApiBackupsUploadResponses[keyof PostApiBackupsUploadResponses];

export type PostApiBackupsByNameRestoreData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/backups/{name}/restore';
};

export type PostApiBackupsByNameRestoreResponses = {
    /**
     * OK
     */
    200: RestoreResult;
};

export type PostApiBackupsByNameRestoreResponse = PostApiBackupsByNameRestoreResponses[keyof PostApiBackupsByNameRestoreResponses];

export type PostApiAuthCustomerRegisterData = {
    body?: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/customer/register';
};

export type PostApiAuthCustomerRegisterResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostApiAuthCustomerRegisterResponse = PostApiAuthCustomerRegisterResponses[keyof PostApiAuthCustomerRegisterResponses];

export type PostApiAuthCustomerLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/customer/login';
};

export type PostApiAuthCustomerLoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostApiAuthCustomerLoginResponse = PostApiAuthCustomerLoginResponses[keyof PostApiAuthCustomerLoginResponses];

export type PostApiAuthCustomerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/customer/refresh';
};

export type PostApiAuthCustomerRefreshResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostApiAuthCustomerRefreshResponse = PostApiAuthCustomerRefreshResponses[keyof PostApiAuthCustomerRefreshResponses];

export type PostApiAuthCustomerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/customer/logout';
};

export type PostApiAuthCustomerLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthCustomerRequestVerificationData = {
    body?: RequestVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/auth/customer/request-verification';
};

export type PostApiAuthCustomerRequestVerificationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthCustomerConfirmEmailData = {
    body?: ConfirmEmailRequest;
    path?: never;
    query?: never;
    url: '/api/auth/customer/confirm-email';
};

export type PostApiAuthCustomerConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthCustomerForgotPasswordData = {
    body?: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/customer/forgot-password';
};

export type PostApiAuthCustomerForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthCustomerResetPasswordData = {
    body?: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/customer/reset-password';
};

export type PostApiAuthCustomerResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAuthCustomerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/customer/me';
};

export type GetApiAuthCustomerMeResponses = {
    /**
     * OK
     */
    200: UserInfo;
};

export type GetApiAuthCustomerMeResponse = GetApiAuthCustomerMeResponses[keyof GetApiAuthCustomerMeResponses];

export type PostApiAuthCustomerChangePasswordData = {
    body?: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/customer/change-password';
};

export type PostApiAuthCustomerChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthCustomerProfileData = {
    body?: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/auth/customer/profile';
};

export type PostApiAuthCustomerProfileResponses = {
    /**
     * OK
     */
    200: UserInfo;
};

export type PostApiAuthCustomerProfileResponse = PostApiAuthCustomerProfileResponses[keyof PostApiAuthCustomerProfileResponses];

export type GetApiMediaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/media';
};

export type GetApiMediaResponses = {
    /**
     * OK
     */
    200: Array<MediaItem>;
};

export type GetApiMediaResponse = GetApiMediaResponses[keyof GetApiMediaResponses];

export type PostApiMediaData = {
    body?: {
        file?: Blob | File;
        alt?: string;
    };
    path?: never;
    query?: never;
    url: '/api/media';
};

export type PostApiMediaResponses = {
    /**
     * OK
     */
    200: MediaItem;
};

export type PostApiMediaResponse = PostApiMediaResponses[keyof PostApiMediaResponses];

export type DeleteApiMediaByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/media/{id}';
};

export type DeleteApiMediaByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMediaByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/media/{id}';
};

export type GetApiMediaByIdResponses = {
    /**
     * OK
     */
    200: MediaItem;
};

export type GetApiMediaByIdResponse = GetApiMediaByIdResponses[keyof GetApiMediaByIdResponses];

export type PutApiMediaByIdData = {
    body?: UpdateMediaRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/media/{id}';
};

export type PutApiMediaByIdResponses = {
    /**
     * OK
     */
    200: MediaItem;
};

export type PutApiMediaByIdResponse = PutApiMediaByIdResponses[keyof PutApiMediaByIdResponses];

export type GetApiMenusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/menus';
};

export type GetApiMenusResponses = {
    /**
     * OK
     */
    200: Array<MenuSummary>;
};

export type GetApiMenusResponse = GetApiMenusResponses[keyof GetApiMenusResponses];

export type PostApiMenusData = {
    body?: CreateMenuRequest;
    path?: never;
    query?: never;
    url: '/api/menus';
};

export type PostApiMenusResponses = {
    /**
     * OK
     */
    200: MenuDetail;
};

export type PostApiMenusResponse = PostApiMenusResponses[keyof PostApiMenusResponses];

export type DeleteApiMenusByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/menus/{id}';
};

export type DeleteApiMenusByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMenusByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/menus/{id}';
};

export type GetApiMenusByIdResponses = {
    /**
     * OK
     */
    200: MenuDetail;
};

export type GetApiMenusByIdResponse = GetApiMenusByIdResponses[keyof GetApiMenusByIdResponses];

export type PutApiMenusByIdData = {
    body?: UpdateMenuRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/menus/{id}';
};

export type PutApiMenusByIdResponses = {
    /**
     * OK
     */
    200: MenuDetail;
};

export type PutApiMenusByIdResponse = PutApiMenusByIdResponses[keyof PutApiMenusByIdResponses];

export type GetApiPagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pages';
};

export type GetApiPagesResponses = {
    /**
     * OK
     */
    200: Array<PageSummary>;
};

export type GetApiPagesResponse = GetApiPagesResponses[keyof GetApiPagesResponses];

export type PostApiPagesData = {
    body?: CreatePageRequest;
    path?: never;
    query?: never;
    url: '/api/pages';
};

export type PostApiPagesResponses = {
    /**
     * OK
     */
    200: PageDetail;
};

export type PostApiPagesResponse = PostApiPagesResponses[keyof PostApiPagesResponses];

export type DeleteApiPagesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/pages/{id}';
};

export type DeleteApiPagesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPagesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/pages/{id}';
};

export type GetApiPagesByIdResponses = {
    /**
     * OK
     */
    200: PageDetail;
};

export type GetApiPagesByIdResponse = GetApiPagesByIdResponses[keyof GetApiPagesByIdResponses];

export type PutApiPagesByIdData = {
    body?: UpdatePageRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/pages/{id}';
};

export type PutApiPagesByIdResponses = {
    /**
     * OK
     */
    200: PageDetail;
};

export type PutApiPagesByIdResponse = PutApiPagesByIdResponses[keyof PutApiPagesByIdResponses];

export type PostApiPagesImportData = {
    body?: ImportPageRequest;
    path?: never;
    query?: never;
    url: '/api/pages/import';
};

export type PostApiPagesImportResponses = {
    /**
     * OK
     */
    200: ImportPageResult;
};

export type PostApiPagesImportResponse = PostApiPagesImportResponses[keyof PostApiPagesImportResponses];

export type PutApiPagesByIdTagsData = {
    body?: UpdatePageTagsRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/pages/{id}/tags';
};

export type PutApiPagesByIdTagsResponses = {
    /**
     * OK
     */
    200: PageDetail;
};

export type PutApiPagesByIdTagsResponse = PutApiPagesByIdTagsResponses[keyof PutApiPagesByIdTagsResponses];

export type PostApiPagesByIdPublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/pages/{id}/publish';
};

export type PostApiPagesByIdPublishResponses = {
    /**
     * OK
     */
    200: PageDetail;
};

export type PostApiPagesByIdPublishResponse = PostApiPagesByIdPublishResponses[keyof PostApiPagesByIdPublishResponses];

export type PostApiPagesByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/pages/{id}/unpublish';
};

export type PostApiPagesByIdUnpublishResponses = {
    /**
     * OK
     */
    200: PageDetail;
};

export type PostApiPagesByIdUnpublishResponse = PostApiPagesByIdUnpublishResponses[keyof PostApiPagesByIdUnpublishResponses];

export type GetApiPublicInstanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/instance';
};

export type GetApiPublicInstanceResponses = {
    /**
     * OK
     */
    200: InstanceConfig;
};

export type GetApiPublicInstanceResponse = GetApiPublicInstanceResponses[keyof GetApiPublicInstanceResponses];

export type GetApiPublicMediaByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/api/public/media/{key}';
};

export type GetApiPublicMediaByKeyErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiPublicMediaByKeyError = GetApiPublicMediaByKeyErrors[keyof GetApiPublicMediaByKeyErrors];

export type GetApiPublicMediaByKeyResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetApiPublicMediaByKeyResponse = GetApiPublicMediaByKeyResponses[keyof GetApiPublicMediaByKeyResponses];

export type GetApiPublicMenusByHandleData = {
    body?: never;
    path: {
        handle: string;
    };
    query?: never;
    url: '/api/public/menus/{handle}';
};

export type GetApiPublicMenusByHandleResponses = {
    /**
     * OK
     */
    200: PublicMenu;
};

export type GetApiPublicMenusByHandleResponse = GetApiPublicMenusByHandleResponses[keyof GetApiPublicMenusByHandleResponses];

export type GetApiPublicPagesBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/public/pages/{slug}';
};

export type GetApiPublicPagesBySlugResponses = {
    /**
     * OK
     */
    200: PublicPage;
};

export type GetApiPublicPagesBySlugResponse = GetApiPublicPagesBySlugResponses[keyof GetApiPublicPagesBySlugResponses];

export type GetApiPublicSiteConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/site-config';
};

export type GetApiPublicSiteConfigResponses = {
    /**
     * OK
     */
    200: SiteConfigResponse;
};

export type GetApiPublicSiteConfigResponse = GetApiPublicSiteConfigResponses[keyof GetApiPublicSiteConfigResponses];

export type GetApiSiteConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/site-config';
};

export type GetApiSiteConfigResponses = {
    /**
     * OK
     */
    200: SiteConfigResponse;
};

export type GetApiSiteConfigResponse = GetApiSiteConfigResponses[keyof GetApiSiteConfigResponses];

export type PutApiSiteConfigData = {
    body?: UpdateSiteConfigRequest;
    path?: never;
    query?: never;
    url: '/api/site-config';
};

export type PutApiSiteConfigResponses = {
    /**
     * OK
     */
    200: SiteConfigResponse;
};

export type PutApiSiteConfigResponse = PutApiSiteConfigResponses[keyof PutApiSiteConfigResponses];

export type PostApiAuthStaffRegisterData = {
    body?: StaffRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/staff/register';
};

export type PostApiAuthStaffRegisterResponses = {
    /**
     * OK
     */
    200: UserInfo;
};

export type PostApiAuthStaffRegisterResponse = PostApiAuthStaffRegisterResponses[keyof PostApiAuthStaffRegisterResponses];

export type PostApiAuthStaffLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/staff/login';
};

export type PostApiAuthStaffLoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostApiAuthStaffLoginResponse = PostApiAuthStaffLoginResponses[keyof PostApiAuthStaffLoginResponses];

export type PostApiAuthStaffRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/staff/refresh';
};

export type PostApiAuthStaffRefreshResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostApiAuthStaffRefreshResponse = PostApiAuthStaffRefreshResponses[keyof PostApiAuthStaffRefreshResponses];

export type PostApiAuthStaffLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/staff/logout';
};

export type PostApiAuthStaffLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAuthStaffMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/staff/me';
};

export type GetApiAuthStaffMeResponses = {
    /**
     * OK
     */
    200: UserInfo;
};

export type GetApiAuthStaffMeResponse = GetApiAuthStaffMeResponses[keyof GetApiAuthStaffMeResponses];

export type PostApiAuthStaffChangePasswordData = {
    body?: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/staff/change-password';
};

export type PostApiAuthStaffChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthStaffProfileData = {
    body?: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/auth/staff/profile';
};

export type PostApiAuthStaffProfileResponses = {
    /**
     * OK
     */
    200: UserInfo;
};

export type PostApiAuthStaffProfileResponse = PostApiAuthStaffProfileResponses[keyof PostApiAuthStaffProfileResponses];

export type GetApiTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type GetApiTagsResponses = {
    /**
     * OK
     */
    200: Array<TagUsage>;
};

export type GetApiTagsResponse = GetApiTagsResponses[keyof GetApiTagsResponses];
